# Personal Financial Planning

## Misc

-   Packages
    -   [{]{style="color: #990000"}[R4GoodPersonalFinances](https://cran.r-project.org/web/packages/R4GoodPersonalFinances/index.html){style="color: #990000"}[}]{style="color: #990000"} - Make informed, data-driven decisions for your personal or household finances.
        -   Use tools and methods that are selected carefully to align with academic consensus, bridging the gap between theoretical knowledge and practical application.
        -   They assist you in finding optimal asset allocation, preparing for retirement or financial independence, calculating optimal spending, and more
-   Resources
    -   FinanceKid video [playlist](https://www.youtube.com/playlist?list=PLAoukTI-9JberNM--SfEl_7sWZfS0ZnsS)
-   Index Funds
    -   Vanguard Total Stock Market, Value Fund, (small percentage) International Fund (The Knowledge Project Podcast, ep 195, Morgan Housel)
        -   Also keeps 10-15% in cash
    -   Money Market Account - Like a savings account except with greater return. Able to write so many checks per month and withdraw up to a certain amount per month. Invests in Treasuries and CDs. Requires a minimum balance of around \$10K.
