# Football {#sec-foot .unnumbered}

## Misc {#sec-foot-misc .unnumbered}

- Packages
  - [{]{style="color: #990000"}[cfbfastR](https://cfbfastr.sportsdataverse.org/){style="color: #990000"}[}]{style="color: #990000"} - API wrapper around <https://collegefootballdata.com/.> Beyond data aggregation and tidying ease, one of the multitude of services that cfbfastR provides is for benchmarking open-source expected points and win probability metrics.
- Resources
  - [CFBTrack College Football Glossary & Stats Dictionary](https://cfbtrack.com/glossary)
  - [CFBD Glossary](https://collegefootballdata.com/glossary)
  - [PFF Signature Statistics Glossary](https://www.pff.com/news/pro-pff-signature-statistics-a-glossary)
  - [cfbfastr vignettes](https://cfbfastr.sportsdataverse.org/articles/index.html) has a series of articles on Expected Points

## Metrics {#sec-foot-met .unnumbered}

- Misc
  - Stats like "yards per rush" can be less informative based on how many games that include garbage time a team has.
    - e.g. Georgia may be ranked lower in rushing yards per play than Ohio State but Ohio State's numbers might be inflated because they played a weak schedule and blew out more teams than Georgia.
  - Clavio doesn't like PFF grades for TEs and WRs as he feels they don't capture enough to be informative.
  - FEI ratings are normally distributed, and one standard deviation is approximately 0.6 on the FEI rating scale, calibrated to equate to a scoring advantage or disadvantage on a neutral field of 0.6 points per possession. ([source](https://bcftoys.com/whiteboard/outliers))
  - In terms of the FEI ranking scale (end-of-season FEI), and now with nearly 140 FBS teams: ([source](https://bcftoys.com/whiteboard/outliers))
    - Average Team - Ranks in the mid-60s
    - Good Team - Ranks in the mid-20s (one standard deviation better than the avg team)
    - Elite Team - Ranks around 5th (two standard deviations better than the avg team)
    - National Champions - Sometimes push into three-sigma (three standard deviations above average) territory.
  - Luck metrics can be useful in win total prediction
    - Example: 2025 Houston (9-3) ([source](https://davidhale.substack.com/p/you-got-lucky-babe))
      - Easiest schedule in the Big 12 (ranked 73rd at the end of the regular season)
      - +12 swing year over year in turnover margin (though they didn’t do nearly enough with those takeaways)
      - Successful play and explosive play rates profiled almost exactly the same as NC State — a team that won 7 regular-season games
      - 6-1 in one-possession games, 4-1 in games decided by a field goal or less, and won 5 games when tied or behind in the fourth quarter
      - Therefore, the luck metrics indicate a lower win total than the 9 in 2025. With the o/u at 8.5 for 2026, the under might be a good bet.
- [Individual]{.underline}
  - **Career Snaps** - The number of plays participated in
- [Team]{.underline}
  - **Average Starting Field Position** (e.g. Own 25.5)
  - **Conversion**
    - Late Down
  - **Efficiency (EF)**
    - **Pass Blocking Efficiency (PBE)** - The number of pressures allowed per pass protection snap with sacks weighted more heavily
    - **Tackling Efficiency** - The number of tackles per "would-be sure" tackling opportunity
  - **Eckel Rate** - How often your offense \[defense\] generates \[allows\] a big play touchdown or a first down inside the 40 on any given drive.
    - These are definitions from a [twitter post](https://x.com/statsowar/status/1709229240720449536?lang=en) by Fleming.
  - **Eckel Ratio** - The percent of total first downs and big play touchdowns in a game that you control
  - **EP (Expected Points)** - Assigns point values to field positions based on down, distance, and yard line. A negative value means the opponent is expected to score next.
  - **EPA (Expected Points Added)** -Uses EP to measure play impact by calculating the change in EP from the start to end of a play
    - per Play or Dropback
    - per Rush
    - Early Downs
  - **Explosive Play Rate**
  - **Garbage Time** - When one of the following is true:
    - Lead \> 38 points in 2nd quarter
    - Lead \> 28 points in 3rd quarter
    - Lead \> 22 points in 4th quarter
  - **Line Yards**
    - per Rush
  - **Points**
    - per Play
    - per Drive
    - per Scoring Opportunity
    - per Eckel - What an offense \[defense\] does \[allows\] given that you \[your opponent\] has a big play touchdown or a first down inside the 40
  - **PPA** - Predicted Points Added; The net point value that a player relative to the down and field position
    - Equivalent to EPA but uses CollegeFootballData.com's custom model (what that model is... ¯\\\_(ツ)\_/¯)
  - **Success Rate** is:
    - 1st Down: Gain $40\%$ of yards to go.
    - 2nd Down: Gain $60\%$ of yards to go.
    - 3rd/4th Down: Gain $100\%$ of yards to go (convert).
    - **Standard Downs** : First downs, second-and-7 or less and third- or fourth-and-4 or less
    - Categories: Passing, Rushing, Early-Down, 3rd Down, etc.
    - per EPA (e.g. Early Down Success / EPA)
  - **Yards**
    - per Point
- Luck
  - Points off Turnover Margin (and YoY change)
  - Fumble Recovery Rate
  - Red-Zone Production
  - Third-and-Short Production
  - Avg Starting Field Position
  - Close Game Record
- [Offense]{.underline}
  - Offensive Line
    - **HIT** - Hits on the QB
    - **QBH** - Hurries where a QB is forced to throw early or scramble
    - **OPP** - Opportunities (aka snaps, reps)
    - **PEN** - Penalties
    - **PR** - Pressures Allowed which is sacks + hits + hurries
    - **SK** - Sacks Allowed
  - Receiving
    - [**1st**]{style="color: #009499"} - Number of First Downs
    - [**ADOT**]{style="color: #009499"} - Average Depth of Target
    - [**CTT**]{style="color: #009499"} - Contested Targets
    - [**CCR**]{style="color: #009499"} - Contested Catch Rate
    - [**DRP**]{style="color: #009499"} - Drop Rate
    - [**MTF**]{style="color: #009499"} - Missed Tackles Forced
- [Defense]{.underline}
  - **Havoc Rate** - Percentage of plays that result in a disruptive negative event. It includes: tackles for loss (TFL), sacks, forced fumbles, interceptions, and pass break ups (PBU).
  - **ST** (Solo Tackles), **AT** (Assisted Tackles)
  - **MT%** - Missed Tackle Percentage
  - **R%** - Reception Percentage; receptions per target
  - **YPR** - Yards per Reception
  - **PBU** - Pass Break-Ups
  - **FF** - Forced Fumbles
