# Insurance {#sec-insur .unnumbered}

## Misc {#sec-insur-misc .unnumbered}

-   Packages
    -   [CRAN Task View](https://cran.r-project.org/web/views/ActuarialScience.html)
-   Also see
    -   [Regression, Other \>\> Censored and Truncated Data](https://ercbk.github.io/Data-Science-Notebook/qmd/regression-other.html#sec-reg-other-censtrunc){style="color: green"} \>\> Examples
-   DS Use Cases
    -   Predict insurance claims frequency (see bkmk)

## Life Tables {#sec-insur-life .unnumbered}

-   Summarizes the mortality and survival patterns of a population. It provides a detailed summary of the expected life span and survival rates of a group of individuals at various ages, based on observed or estimated mortality rates.

-   Misc

    -   Packages
        -   [{]{style="color: #990000"}[rwlifetable](https://cran.r-project.org/web/packages/rwlifetable/index.html){style="color: #990000"}[}]{style="color: #990000"} - Estimation of Life Tables Using Rolling Windows
            -   Estimates life tables, specifically (crude) death rates and (raw and graduated) death probabilities, using rolling windows in one (e.g., age), two (e.g., age and time) or three (e.g., age, time and income) dimensions.
        -   [{]{style="color: #990000"}[BaSTA](https://cran.r-project.org/web//packages//BaSTA/index.html){style="color: #990000"}[}]{style="color: #990000"} - Age-Specific Bayesian Survival Trajectory Analysis from Incomplete Census or Capture-Recapture/Recovery Data
            -   Includes tools for data checking, model diagnostics and outputs such as life-tables and plots

-   Components

    -   **Age Intervals** ($x$): Specifies the age groups or intervals (e.g., 0–1, 1–4, 5–9, etc.).
    -   **Number Alive** ($l_x$): The number of individuals alive at the beginning of each age interval, starting with a hypothetical cohort (e.g., 100,000 births).
    -   **Probability of Death** ($q_x$): The probability that an individual dies during the age interval.
    -   **Number of Deaths** ($d_x$): The number of individuals who die during each age interval.
    -   **Survival Rate** ($p_x$): The probability that an individual survives through the age interval.
    -   **Person-Years Lived** ($L_x$): The total number of years lived by the cohort during an age interval.
    -   **Total Remaining Life Expectancy** ($T_x$): The total number of person-years remaining for the cohort at the beginning of a given age.
    -   **Life Expectancy** ($e_x$): The average number of additional years an individual at a certain age is expected to live.

-   Types

    -   **Complete Life Table:** Includes data for every single year of age.
    -   **Abridged Life Table:** Groups ages into broader intervals, such as 5 or 10 years, to simplify calculations.
    -   **Cohort (Longitudinal) Life Table:** Tracks a specific cohort over time.
    -   **Period Life Table:** Represents the mortality experience of a population at a specific point in time, assuming current mortality rates remain constant.

## Risk {#sec-insur-risk .unnumbered}

-   When analyzing data, beware of survivorship bias
    -   Example: Real Estate Investment
        -   An analyst is studying housing prices over time in a certain region. They use a current map and so only consider neighborhoods that have survived without major incidents (like natural disasters, economic decline, etc.). They will probably underestimate the risk and overestimate the return of real estate investment in that region.
-   Limiting exposure
    -   From <http://ronaldrichman.co.za/2021/02/24/x-is-not-fx-insurance-edition/>
    -   Severity
        -   Capping the payout of a policy
            -   e.g. only paying a maximum amount if tragedy strikes
    -   Frequency
        -   Setting a threshold to which the policy only pays out after the threshold has been passed
            -   Keeps the insurance company from being needled to death by administrative costs of frequent policy payouts
            -   e.g. minor doctor appointments
    -   Reinsurance
        -   Policies that produce an option-like exposure, where one can pass risk above a fixed level of losses to the counterparty for a fixed premium (excess of loss). Other options are to share risks in more or less equal proportions.
            -   Allows insurers take on risky (and potentially more profitable) policies by taking on an insurance policy themselves for the excess risk
                -   airplanes, volatile manufacturing, etc.
-   Analysis
    -   Fit one distribution to the smaller and more frequent attritional losses, and another disruption to the extreme losses, with the latter distribution often motivated by extreme value theory
        -   This approach ignores the fact the each loss has an upper bound determined by the limits on the policy generating the loss. Also, since these extreme losses follow a very heavy tailed distribution, naïve estimators of the statistical properties of these losses are likely to be biased
    -   Shadow Moments
        -   Transform the data to a new domain that is unbounded, parameterizing EVT distributions in this domain, and then translating the implications of these models back to the original bounded domain
        -   Cirillo, P., & Taleb, N. N. (2016). On the statistical properties and tail risk of violent conflicts. Physica A: Statistical Mechanics and Its Applications, 452, 29--45. https://doi.org/10.1016/j.physa.2016.01.050
        -   Cirillo, P., & Taleb, N. N. (2020, June 1). Tail risk of contagious diseases. Nature Physics, Vol. 16, pp. 606--613. https://doi.org/10.1038/s41567-020-0921-x

## Market Basket Analysis {#sec-insur-mba .unnumbered}

-   Support: What percent of patients have disease 1 and disease 2?
-   Confidence: Of the people w/disease1, what percent also have disease 2?
-   Lift: How much more likely are you to have disease 2 if you already had disease 1 (and vice versa)
