# KPIs {#sec-kpis}

## Misc

-   Also see
    -   [Job, Organizational and Team Development](Job,%20Organizational%20and%20Team%20Development) \>\> Developing a data strategy \>\> Objectives and Key Results (OKRs)
    -   [Product Development](Product%20Development) \>\> Metrics
-   Leaders should focus on 3 to 6 KPIs that will drive growth.
-   When a KPI's growth begins to stagnate, break up the KPI monolith into smaller, more meaningful (and hopefully, easier to optimize) segments

## Terms

-   [**Operationalization**]{style="color: #009499"} - a process of defining the measurement of a phenomenon that is not directly measurable (e.g. happiness), though its existence is indicated by other phenomena. It is the process of defining a fuzzy concept so as to make the theoretical concept clearly distinguishable or measurable, and to understand it in terms of empirical observations.

## General

-   KPI characteristics

    -   Monotonic: you always want to drive them higher or lower
    -   Typically a summary statistic or rate

-   Question that you should ask when determining which metrics should be your KPIs What do you want to know?

    ```         
      How much do you need to know?

      Why do you want to know this?

      What is the value or impact between not knowing and knowing?
    ```

-   "Input --\> Output --\> Outcome" framework

    -   Input Metrics
        -   Provide information about the resources used to create a system or process
        -   Useful for evaluating the efficiency of a system or process
        -   What you control: amount of time you spend on a task, the quantity of materials used to produce something, etc.
        -   Outputs should be highly responsive to your inputs
    -   Output Metrics
        -   Provide information about the immediate results of a system or process
        -   Useful for evaluating the performance of a system or process
            -   Answers whether the system or process is producing the desired results.
        -   It should be clear how much your output would change for one additional unit of input.
        -   Very actionable but not fully under your control
        -   There is a causal link between your output and your outcome, so difficult to discover
            -   May require experimentation to determine causality
        -   Typically tracked daily
    -   Outcome Metrics
        -   North Star metrics (See Product Metrics \>\> Types)
        -   What you are aiming to move with all your activities.
        -   Typically requires multiple outputs to move
        -   Typically tracked monthly or quarterly
    -   [Example]{.ribbon-highlight}: Educational Program
        -   The \# of teachers, their average seniority, the funding of the school (inputs) help drive the grades of the students and their consistency over time higher (output) which ultimately lead to more students graduating high school (outcomes).

-   Industry examples

    -   Financial --- Revenue growth, cash flow, burn rate, gross profit
    -   Customer --- Engagement rates, net promoter scores, acquisition costs, conversion rates
    -   Support & Service --- Turnaround time, mean time to resolve, SLA compliance, quality
    -   Employee --- Attrition and retention, satisfaction, engagement
    -   Governance, Risk, & Compliance --- Percent compliance to process, audit compliance, non-security incidents Issues
    -   Avoid incentivizing the wrong behavior
        -   As soon as someone's performance is linked to a metric --- it is fair game to expect them to try to move the metric, so it is up to the metric designer to make sure the 'rules of the game' are clearly articulated.
        -   [Example]{.ribbon-highlight}: Reducing the number of support tickets opened via email
            -   Potential Solution: Engineer makes it as hard as possible to contact the email support
            -   Unintended Consequence: Increasing the number of 'negative' social media interactions
        -   [Example]{.ribbon-highlight}: You don't want to push your salespeople to sell without caring about the retention rate.
            -   e.g Car salesmen selling a lemon to a customer. Customer unlikely to return to buy another car.
        -   Solutions
            -   Pair metric with a guardrail metric (see Product Metrics \>\> Types)
                -   Examples
                    -   quantity (sales) + quality (retention rate)
                    -   short term metric (inventory level) + long term metric (# of shortages)
            -   Design a compound metric
                -   By taking into account multiple measurement, it cannot be easily gamed
                -   Can also include metrics you don't want move negatively (e.g. cost metrics, guardrail metrics, health metrics)
                -   For experiments that use this metric, you then create a binary decision rule to decide if your experiment is successful or not.
    -   Beware of Deceptive Metrics
        -   Correlation does not equal causation
        -   [Example]{.ribbon-highlight}: Someone discovers that the \# of transactions is correlated w/higher revenue
            -   Company decides to make \# of transactions a metric and starts trying to increase it.
                -   e.g. re-targeting former customers, offering discounts, etc.
            -   Revenue doesn't substantially increase after considerable effort and resources
            -   Analysis reveals that the revenue is being mostly driven by a few whales buying high-ticket items while the team's increase in transactions was mostly low-ticket items
            -   So, the strategy should've been to target more whales and not just trying to increase the \# of transactions

-   Checks

    -   Metric is precise (i.e. measurement isn't noisy)
    -   Metric is accurate (i.e. it properly depicts the phenomenon it is supposed to depict).

-   Next Steps

    -   Figure out the best way to calculate these metrics
    -   Create dashboards to monitor them over time
    -   Set up alerts when thresholds are crossed
        -   anomaly detection

## Product Metrics

-   Why are they important?
    -   Metrics help companies have clarity, alignment and prioritization in what to build.
    -   Metrics help a company decide how to build the product once they've prioritized what to build.
    -   Metrics help a company determine how successful they are and hold them accountable to an outcome.
-   Types
    -   **North Star Metric (NSM)**
        -   Long-term metric focused on the desired outcome for the entire company
        -   Examples of potential NSMs
            -   Instagram: Monthly Active Users
            -   Spotify: Time Spent Listening
            -   Airbnb: Booked Nights
            -   Lyft: Rides per week
            -   Slack: Daily Active Users
            -   Customer happiness (e.g. revenue, Net Promoter Score (NPS), and customer satisfaction)
            -   Quora: Questions Answered
    -   **Primary**
        -   Ask
            -   "what is the desired outcome for this product?" (keeping the company's mission in mind)
                -   [Example]{.ribbon-highlight}: number of high quality sellers that join the platform as a result of the email outreach
            -   "What do our customers care about, and how do we solve it as fast as possible?"
                -   Example
                    -   Engineering, product, and marketing agree that onboarding is a pain point, you decide to build goals and KPIs around making it easier for new customers to get started.
                    -   Align the company around the shared goal of reducing new tool onboarding from five days to three days
                        -   Data team gathers metrics on usage and helps build A/B tests
                        -   Engineering team modifies the product
                        -   Marketing team creates nurture campaigns
        -   Map this outcome to a metric that is meaningful, measurable, and movable
            -   Meaningful
                -   Should reflect the way a company intends to drive value for its customers (based on the company's *mission*)

                -   Avoid *vanity* metrics.

                    -   [Example]{.ribbon-highlight}: Quora uses push notifications to alert users when they would be best suited to answer a question. However, the number of times users click on the notification and open the app is a vanity metric. It may make Quora feel good to see open rates going up. But Quora didn't release push notifications to drive open rates. The outcome they were aiming for was to get high quality answers to questions asked on their platform. So an outcome oriented metric would focus on answer rates, not open rates.
            -   Measurable
                -   Each component of that metric's formula should be a datapoint that you can collect with high confidence and precision. And remember to add a time frame to your metric.
                -   Some aspects of a company's or product's mission/goal aren't measurable directly but may be measured through latent variables, proxy, or highly associated variable or group of variables
            -   Moveable
                -   Basically means the metric shouldn't be so noisy as to inhibit being able to measure changes when you take actions to change it.
                -   The metric should measure something that as directly under control of the company as possible.
                    -   [Example]{.ribbon-highlight}: Page Load Time - time difference between a user clicking on a link or typing the URL in the browser and the page being rendered to the user.
                        -   This is affected substantially by the user's computer, ISP, browser, etc. along with the app/website code. So asis, it wouldn't be a good metric to track.
            -   Other Desirables
                -   Quick Feedback
                    -   Actions taken to influence the metric should be (almost) immediately observable
                    -   [Example]{.ribbon-highlight}: Measuring (subscription) retention would require you to wait until the end of the month in order to be able to judge the effect of your action. Daily Active Users might be a better alternative
                -   Easily Interpretted
                    -   The role of a metric is to align teams around a specific goal so that they can take the right steps towards achieving that goal. If people can't understand the metric, they can't take the right steps to optimize for it.
                    -   Examples:
                        -   Complicated: the median of a weighted combination of viewing time, comments, likes, shares per user (with each action having different weights based on its importance)
                        -   Simpler: average watch time per user.
                -   Not Gameable
                    -   I.e. picking an easily moveable metric that has no real value leads to bad incentives.
    -   **Supporting/Tracking/Input Metrics**
        -   Leading indicators that the NSM or the primary metric is moving in the right direction
        -   Inputs into the NSM and are directly correlated to its value
        -   Also tells you where your efforts to move your NSM may be falling short.
        -   Examples
            -   Number of emails sent
            -   The number of people that opened the email
            -   Number of businesses that signed up to sell on the platform
    -   **Counter Metrics/Guardrails**
        -   Other outcomes that the business cares about, which may be negatively affected by a positive change in the primary metric (or NSM)
        -   They exist to make sure that in the pursuit of your primary metric, you are not doing harm to another aspect of the business
        -   Example (email marketing to obtain quality sellers for Amazon)
            -   if your primary metric focuses on product *quantity*, your guardrail metric might be around product *quality*
            -   The guardrail, average number of purchases a user makes in a day, ensures that the influx of sellers that the primary metric optimizes for doesn't result in consumers becoming so overwhelmed by choice, that they end up not buying anything at all
-   User journey: **AARRR** (or Pirate Metric) Framework
    -   **Awareness**: How many people are aware your brand exists?
        -   metric examples: number of website visits, social media metrics (number of likes, shares, impressions, reach), time spent on a website, email open rate
    -   **Acquisition**: How many people are interacting with your product?
        -   A **lead** is any potential user who's information you've been able to capture in some shape or form.
            -   e.g. people who give you their email addresses when they sign up for your mailing list are considered to be leads.
        -   A **qualified lead** when they show additional interest in your product beyond giving you their information.
            -   e.g. in addition to signing up for your mailing list they also watch a webinar or sign up for a demo
        -   metric examples: number of leads, number of qualified leads, sign ups, downloads, install, chatbot interactions
    -   **Activation**: How many people are realizing the value of your product?
        -   typically in the form of an *action taken x times with in a period of y days*
        -   When the activation hurdle is crossed, an individual goes from unknown entity to actual user.
        -   Example (Dropbox): Their activation metric is the number of users that have stored at least one file in one dropbox folder on one device
        -   metric examples: number of connections made, number of times an action is performed, number of steps completed
    -   **Engagement**: What is the breadth and frequency of user engagement?
        -   Depth of their usage: How often are they using your product? Is it above or below the average users frequency?
        -   Breadth of their usage: Are they performing every action that's possible with your product? Are they favoring some more than others? What if you have multiple products? Are they using all of them?
        -   metric examples: daily, weekly and monthly active users, time spent in a session, session frequency, actions taken in the product
    -   **Revenue**: How many people are paying for your product?
        -   \*\* Remember, a business should optimize for the value they bring to their customers, not the revenue they generate. And, if their customers are deriving a lot of value from the business, willingness to pay will be a natural byproduct
        -   metric examples: % of paid customers; average revenue per customer; conversion rate of trial to paid customers; number of transactions completed; shopping cart abandonment rates; ad-metrics like click-through-rate and conversion rate (crucial for ads based businesses)
    -   **Retention/Renewal**: How often are your people coming back?
        -   metric examples: % of users coming back to your platform each day, month, year (product dependent); churn rates; customer lifetime value
    -   **Referral**: How many customers are becoming advocates?
        -   metric examples: [*Net Promoter Score*](https://www.netpromoter.com/know/), [viral coefficient](https://www.questionpro.com/blog/viral-coefficient/) i.e. the average number of people that your users refer you to
            -   Also see
                -   [Survey, Design](Survey,%20Design) \>\> Response Scales \>\> Net Promoter Score
                -   [Algorithms, Product](Algorithms,%20Product) \>\> Net Promoter Score
