# Sports Betting {#sec-spbet .unnumbered}

## Misc {#sec-spbet-misc .unnumbered}

-   BetCris, Bookmaker, and Pinnacle are market makers. Best to use their closing lines.
    -   Also, if at any time you find a line better at Bookmaker or another site than is offered at Pinnacle you might have a smart bet. The next step would be to return to this page and calculate Pinnacle's No-Vig price. If the odds you're getting are better than Pinnacle's no-vig price chances are you have a +EV (positive expected value) wager.
-   A move from -110 to -120 raises the break-even point from 52.38% to 54.55% (i.e Fair Value Odds but given as implied probabilities here)
-   Steps to avoid getting picked off by bookmakers
    -   These are actions that sharp bettors take that bookmakers used to help identify them.
    -   Notes from [Eliminate These Five Sharp Betting Tells From Your Game](https://unabated.com/articles/eliminate-these-five-sharp-betting-tells-from-your-game?ref=thepowerrank)
    -   Sharps tend to bet early and help shape a stronger line for books to present to the less-knowledgeable public betting crowd who will bet later.
        -   Solution: Instead of always betting when the opening line is published, bet when key events for that sport take place (e.g. when NFL injury report is published, when an informative site/person posts their report/info, etc.).
    -   Sharps tend to bet more underdogs than the public
        -   Public bettors like to bet on overs or the expected favorite to win the game. As a result, sharp bettors often find value in betting unders or underdogs
        -   Due to betting markets becoming more efficient, the Unders/Underdogs value is dissipating. In major sports, the underdog is covering right around 50-51% of the time. As a result, finding value on Overs/Favorites is possible.
        -   Solution: Keep records of the types of bets you make with each book. If you're betting more underdogs at a book, change your behavior which can be as simple as not betting there for a few days. Perhaps betting something in an unrelated sport. Or, when necessary, bet something without getting the best number in the market.
    -   Sharps tend to bet in amounts that return round numbers (e.g. bet \$110 to win \$100)
        -   Solution: Toss in some weird bet amounts make you look like you have less of a system.
    -   Sharps tend to bet straight bets only
        -   Solution: Mix in some parlays in positive expected value situations
    -   Sharps tend to get good Closing Line Value

## Terms {#sec-spbet-terms .unnumbered}

-   [**Closing Line Value (CLV)**]{style="color: #009499"} - A measure of the value of a bet at the time it is placed compared to the closing odds. You can calculate it by comparing the odds you received when you placed your bet to the final odds when the event starts. If the odds you received were better than the closing odds, then the bet has positive CLV. If the odds you received were worse than the closing odds, then the bet has negative CLV. This is the formula used by the [Unabated](https://unabated.com/articles/getting-precise-about-closing-line-value) website.

    $$
    \text{CLV} = \frac{p_{\text{imp}}^{\text{cl}} - p_{\text{imp}}^{\text{bet}}}{p_{\text{imp}}^{\text{bet}}}
    $$

    -   $p_{\text{imp}}^{\text{cl}}$: Implied probability of the closing line
    -   $p_{\text{imp}}^{\text{bet}}$: Implied probability of your bet

-   [**First Five**]{style="color: #009499"} - Betting an event will happen at the end of five innings of a baseball game

    -   e.g. Over 5.5 points, Braves leading, etc.

-   [**Implied Probability**]{style="color: #009499"} - Is Risk/Reward. Used in betting to obtain a probability converted from a [Moneyline]{.underline} odds

    -   For a negative Moneyline Odds

        $$
        p_{\text{imp}} = \frac{\text{Risk}}{\text{Reward}} = \frac{-\text{Odds}_{\text{mon}}}{-\text{Odds}_{\text{mon}} + 100}
        $$

    -   For a positive Moneline Odds

        $$
        p_{\text{imp}} = \frac{\text{Risk}}{\text{Reward}} = \frac{100}{\text{Odds}_{\text{mon}} + 100}
        $$

-   [**Moneyline**]{style="color: #009499"} - A moneyline bet functions as a straight-up wager on which team will win a game. This kind of bet doesn't involve a point spread.

    -   The underdog on the moneyline pays out at greater odds than the favorite.
    -   Sportsbooks generally display the moneyline, point spread, and total (Over/Under) odds for a game, but all three function as separate bets.

-   [**Originators**]{style="color: #009499"} - A sharp that generates their own odds --- the quants of sports betting.

-   [**Picking Off**]{style="color: #009499"} (aka [**Stake Factoring**]{style="color: #009499"}) - The limiting of the maximum wager or even banning of a sharp bettor by a bookmaker. This is done by the bookmaker to optimize profitability. Bettors can be flagged as unprofitable not only by how much or how often they win, but by betting actions determined to be predictive according to the algorithm used by the bookmaker.

-   [**Sharp Bettors**]{style="color: #009499"} (aka [**Sharps**]{style="color: #009499"}) - Informed, experienced, successful sports bettors. Someone who is consistently making positive Expected Value (EV) bets or bets that are expected to be profitable in the long term which is typically means winning about 55% to 60% of the time.

-   [**Tissue**]{style="color: #009499"} - A list of odds representing the chance of the various possible outcomes of a sporting event occurring.

-   [**Totals**]{style="color: #009499"} - The Over/Under

-   [**Tout**]{style="color: #009499"} - An individual (handicapper) who sells picks often in exchange for an up-front payment. Touts either sell picks by themselves or are part of a service, which is composed of numerous touts, selling different kinds of packages.

    -   Can also refer to public handicappers in a public forum, such as in a digital or print newspaper, on social media or on broadcast outlets
    -   Almost never a good idea to buy picks from a tout. Although, if they're good and move lines, you can take advantage of the information to hedge. (See [Is There Ever a Good Reason To Buy Sports Picks?](https://unabated.com/articles/buying-sports-picks-reasons))

-   [**Vigorish**]{style="color: #009499"} (aka [**Vig**]{style="color: #009499"} or [**Juice**]{style="color: #009499"}) - The house edge. Sports betting sites need to turn a profit, so they work a slight advantage into each bet.

## Calculating CLV {#sec-spbet-calcclv .unnumbered}

-   Misc

    -   Notes from
        -   [What is Closing Line Value (CLV)?](https://www.dratings.com/what-is-closing-line-value-clv-and-how-do-you-calculate-it/)
        -   [No-Vig Fair Odds Calculator](https://sportsbettingsites.org/betting-tools/no-vig-calculator/)
        -   [Getting Precise About Closing Line Value](https://unabated.com/articles/getting-precise-about-closing-line-value)
    -   [Using CLV as a metric is only useful when the betting market is efficient.]{.underline} When the true price of the bet isn't actually being discovered, any CLV you see is, at best, an informed guess. When the market is efficient, the closing line converted into probabilities is the most accurate prediction of a match up.
        -   The efficient market hypothesis says that markets eventually reveal the true price of an asset by accounting for all relevant information.
        -   In an efficient market, a negative ROI but a positive CLV says I'm on the right track.
        -   If there aren't enough bettors, in general, betting a particular sport or a particular sportsbook, then it will **not** be efficient
        -   If there aren't enough sharps betting a particular sport or particular sportsbook, then it will **not** be efficient
    -   Examples of efficient betting markets
        -   NFL
    -   Examples of inefficient betting markets
        -   Non-conference season in NCAA basketball (fewer books, low quality info about teams keeps sharps away)
        -   WNBA (low limits keep sharps away)
        -   NBA Player Props (low limits keep sharps away)

-   Steps

    1.  Calculate implied probabilities for moneyline odds you bet and the moneyline odds at close
    2.  Remove the vig from the closing line implied probability
    3.  Calculate the CLV

-   [Example]{.ribbon-highlight}: Calculate CLV

    -   We bet the Tampa Bay Lightning at -195 (Moneyline) odds to beat the Kraken which are at +190. Right before puck drops, what's our CLV if the line shifts to Tampa Bay -220?

    -   Calculate implied probabilities

        $$
        \begin{align}
        p_{\text{imp}}^{\text{bet}} &= \frac{-(-195)}{-(-195) + 100} = 0.661\\
        p_{\text{imp}}^{\text{cl}} &= \frac{-(-220)}{-(-220) + 100} = 0.688\\
        \end{align}
        $$

    -   Calculate the total implied probability

        $$
        \begin{align}
        p_{\text{imp}}^{\text{opp}} &= \frac{100}{190+100} =  0.345\\
        p_{\text{tot}} &= 0.661 + 0.345 = 1.006
        \end{align}
        $$

        -   $p_{\text{imp}}^{\text{opp}}$ is the implied probability of the team you bet against (i.e. opponent).

    -   Calculate adjusted closing implied probability

        $$
        p_{\text{adj}}^{\text{cl}} = \frac{0.688}{1.006} = 0.684
        $$

    -   Calculate CLV

        $$
        \text{CLV} = \frac{0.684 - 0.661}{0.661} = 0.035 \;\;\text{or}\;\; 3.5\%
        $$

-   [Example]{.ribbon-highlight}: Calculate Fair Value Odds and Interpret

    -   Calculate adjusted implied probability for each team

        $$
        \begin{align}
        \text{(Lightning)}\: p_{\text{adj}}^{\text{}} &= \frac{0.661}{1.006} = 0.657 \\ 
        \text{(Krakens)}\: p_{\text{adj}}^{\text{}} &= \frac{0.345}{1.006} = 0.343
        \end{align}
        $$

    -   Convert to probabilities to Moneyline odds

        $$
        \begin{align}
        \text{(Lightning/Favorite)}\: \text{Odds}_{\text{mon}} &= -100 \cdot \frac{p_{\text{adj}}}{1-p_{\text{adj}}} = -100 \cdot \frac{0.657}{1-0.657} = -192\\
        \text{(Krakens/Underdog)}\: \text{Odds}_{\text{mon}} &= 100 \cdot \frac{1-p_{\text{adj}}}{p_{\text{adj}}} = 100 \cdot \frac{1-0.343}{0.343} = 192
        \end{align}
        $$

    -   This means that any moneyline odds

        -   For the favorite, with odds \> -192 (e.g. -191) has a positive Expected Value (EV)
        -   For the underdog, odds \> 192 has a positive Expected Value (EV)

## Betting Strategies {#sec-spbet-betstrat .unnumbered}

-   [Round Robin]{.underline}
    -   Notes from [The Round Robin Bet: The Variance-Reducing Parlay Play](https://unabated.com/articles/the-round-robin-bet-the-variance-reducing-parlay-play)

    -   Parlay betting strategy

    -   Probably won't reach the dexponential returns of a parlay, but it's a solid workhorse than can help bettors reduce the substantial variance inherent in parlay betting while still keeping them alive in the hunt for a more significant payday.

        -   Variance in Parlay Betting
            -   Parlays are hard to hit. In a five-leg parlay, there are 31 ways to lose and only one way to win.
            -   If every leg of a 5-leg parlay had a 50% probability of hitting, you'd win 3.13 percent of the time --- for 3-leg, 12.5% of the time.
            -   Betting round robins just reduces the variance while maintaining the edge for sportsbook. On the flip side, they're good for the player because they reduce variance.
        -   Drawbacks
            -   Likely less of a payout than a regular parlay
            -   You're putting substantially more money on the line
                -   If you want to keep to your original stake, you have to divide it by the number of combinations you're betting.

    -   You create combinations of a group of bets where the total number of combinations is:

        $$
        _nC_r = \frac{n!}{r!(n-r)!}
        $$

        -   $n$: The total number of bets
        -   $r$: The number of bets in each combination

    -   Choosing the optimal number of bets for each combination

        -   If you want to maximize plus-EV spots in a way that decreases fluctuations in your bankroll, choosing round robins with fewer combinations can be a viable path. (e.g. 2 at a time)
        -   No matter how many legs per combination you choose, you'll have to win the same proportion of bets to be profitable.
            -   e.g. For five bets, whether you use 2-leg or 3-leg parlays per combination, you still have to win 4 out 5 bets to be profitable. (See examples)

    -   [Example]{.ribbon-highlight}: 3-Bet Round Robin by Twos (i.e. 3 bets chosen 2 at a time)

        -   Bet Team A & Team B
        -   Bet Team A & Team C
        -   Bet Team B & Team C

    -   [Example]{.ribbon-highlight}: 5 bets chosen 3 at time

        -   Bets

            -   Minnesota Twins moneyline (+102)
            -   New York Yankees moneyline (-158)
            -   Dodgers-Cubs Over 11 (-110)
            -   Rockies-Philles first 5 Over 5.5 (+106)
            -   Luke Weaver (CIN) Over 3.5 strikeouts (-126)

        -   Together as a five-leg parlay, these bets would pay +2226. Bet \$10 to win \$222.67.

        -   Total number of combinations

            $$
            _5\text{C}_3 = \frac{5!}{3!(5-3)!} = \frac{120}{6(2)} = 10
            $$

        -   Round Robin (Bets, payout):

            1.  Twins-Yankees-Cubs Over, which pays \$52.97
            2.  Twins-Yankees-Rockies Over, \$57.95
            3.  Twins-Yankees-Weaver, \$49.16
            4.  Twins-Cubs Over-Rockies Over, \$69.44
            5.  Twins-Cubs Over-Weaver, \$59.17
            6.  Twins-Rockies Over-Weaver, \$64.64
            7.  Yankees-Cubs Over-Rockies Over, \$54.22
            8.  Yankees-Cubs Over-Weaver, \$45.91
            9.  Yankees-Rockies Over-Weaver, \$50.33
            10. Cubs Over-Rockies Over-Weaver, \$60.54

        -   If every leg comes in the max payout is \$564.34. Hit four legs but not Weaver and that would pay \$234.58.

            -   If Weaver and the Rockies miss, you'd only get back \$52.97 for the one combination that connected or you could get back as much as \$69.44 if Yankees and Weaver don't cover.

    -   [Example]{.ribbon-highlight}: 5 bets chosen 2 at a time

        -   Same bets as previous example

        -   Total number of combinations remains the same

        -   For a straight 5 team parlay, assume payout of \$253 for a \$10 stake

            -   I googled the average payouts to get these numbers

        -   Round Robin (Bets, Assuming payout of \$2.60 per \$1 bet for each leg):

            1.  Twins-Yankees, which pays \$26.00
            2.  Twins-Cubs Over
            3.  Twins-Rockies Over
            4.  Twins-Weaver
            5.  Yankees-Cubs Over
            6.  Yankees-Rockies Over
            7.  Yankees-Weaver
            8.  Cubs Over-Rockies Over
            9.  Cubs Over-Weaver
            10. Rockies Over-Weaver

        -   If every leg comes in, the max payout is \$260

        -   If one bet misses(e.g. Twins), the payout is \$156.

        -   If two bets miss (e.g. Twins, Yankees), the payout is \$78 which is still a loss and is probably about \$10 less than the 3-leg approach, but substantially less of a payout if you only miss either 0 or 1 bets.
