project:
  type: book

book:
  title: "Domain Knowledge"
  author: "Eric Book"
  date: "6/21/2023"
  favicon: images/dk-favicon-32.png
  reader-mode: true
  repo-url: https://github.com/ercbk/Domain-Knowledge-Notebook
  page-footer:
    background: "#fffaf0"
    foreground: "#1E4477"
    center: 
      - href: LICENSE.qmd
  sidebar: 
    collapse-level: 1
    background: "#fffaf0"
    foreground: "#1E4477"
    tools: 
      - icon: house-fill
        href: https://ericbook.netlify.app/
  chapters:
    - index.qmd
    - qmd/agriculture.qmd
    - qmd/banking-credit.qmd
    - qmd/budget-allocation.qmd
    - qmd/economics.qmd
    - qmd/environment.qmd
    - qmd/epidemiology.qmd
    - part: "Finance"
      chapters: 
        - qmd/finance-glossary.qmd
        - qmd/finance-investing.qmd
        - qmd/finance-valuation.qmd
    - qmd/healthcare.qmd
    - qmd/insurance.qmd
    - qmd/kpis.qmd 
    - qmd/location-selection.qmd
    - part: "Logistics"
      chapters: 
        - qmd/logistics-demand-planning.qmd
        - qmd/logistics-inventory-management.qmd
        - qmd/logistics-supply-chain.qmd
    - qmd/low-hanging-fruit.qmd
    - qmd/manufacturing.qmd
    - qmd/marketing.qmd
    - qmd/meteorology.qmd
    - qmd/nonprofits.qmd
    - qmd/politics.qmd
    - qmd/product-development.qmd
    - qmd/real-estate.qmd
    - qmd/retail.qmd
    - qmd/saas.qmd
    - qmd/sports-betting.qmd

format:
  html:
    toc-depth: 5
    theme: paper
    css: styles.css
    code-link: true
    backgroundcolor: "#fffaf0"
    fontcolor: "#404d59"
    mainfont: 'Lora'
    monofont: 'Fira Code Retina'
    linkcolor: '#0064B6FF'
    highlight-style: printing

editor: visual

execute:
    freeze: auto